// Конфигурация заданий по категориям
window.AppTasksConfig = {
  daily: [
    {
      code: 'D_DAILY',
      title: 'Ежедневный вход',
      desc: 'Зайди в бота хотя бы один раз за день.',
      xp: 2,
      sms: 0,
      promo: null,
      check_type: 'auto',
      status: 'pending',      // пока заглушка
    },
    {
      code: 'D_REQ_DAILY',
      title: 'Ежедневный запрос',
      desc: 'Сделай минимум один запрос боту в течение дня.',
      xp: 3,
      sms: 0,
      promo: null,
      check_type: 'auto',
      status: 'pending',
    },
  ],

  activity: [
    {
      code: 'D_1',
      title: 'Подписка на канал',
      desc: 'Подпишись на новостной канал проекта, чтобы получать обновления и акции.',
      xp: 10,
      sms: 1,
      promo: null,
      check_type: 'auto',
      status: 'pending',
    },
    {
      code: 'D_2',
      title: 'Подписка и отзыв',
      desc: 'Подпишись на наш новостной канал и оставь честный отзыв о проекте.',
      xp: 30,
      sms: 10,
      promo: null,
      check_type: 'manual',
      status: 'pending',
    },
    {
      code: 'D_3',
      title: 'Активность 7 дней',
      desc: 'Будь активна 7 дней подряд: минимум один запрос боту каждый день.',
      xp: 30,
      sms: 5,
      promo: '5%',
      check_type: 'auto',
      status: 'pending',
    },
    {
      code: 'D_4',
      title: 'Активность 14 дней',
      desc: 'Сохраняй активность 14 дней подряд — бот всегда под рукой.',
      xp: 80,
      sms: 15,
      promo: '10%',
      check_type: 'auto',
      status: 'pending',
    },
    {
      code: 'D_5',
      title: 'Активность 30 дней',
      desc: '30 дней с практикой и подсказками от бота — мягкое, но устойчивое движение вперёд.',
      xp: 150,
      sms: 30,
      promo: '15%',
      check_type: 'auto',
      status: 'pending',
    },
  ],

  referral: [
    {
      code: 'REF_1',
      title: 'Пригласить 3 друзей',
      desc: 'Поделись своей реферальной ссылкой и пригласи минимум 3 друзей по ссылке.',
      xp: 70,
      sms: 10,
      promo: '5%',
      check_type: 'auto_ref',
      status: 'pending',
    },
    {
      code: 'REF_2',
      title: 'Пригласить 7 друзей',
      desc: 'Расскажи о боте тем, кому он может быть полезен, и приведи 7 друзей по своей ссылке.',
      xp: 120,
      sms: 15,
      promo: '10%',
      check_type: 'auto_ref',
      status: 'pending',
    },
    {
      code: 'REF_3',
      title: 'Пригласить 15 друзей',
      desc: 'Продолжай делиться ссылкой: 15 активных приглашений — хороший вклад в развитие проекта.',
      xp: 220,
      sms: 35,
      promo: '20%',
      check_type: 'auto_ref',
      status: 'pending',
    },
    {
      code: 'REF_4',
      title: 'Пригласить 30 друзей',
      desc: 'Ты создаёшь целое мини‑сообщество вокруг Esoteric AI — пригласи 30 друзей по ссылке.',
      xp: 370,
      sms: 75,
      promo: '25%',
      check_type: 'auto_ref',
      status: 'pending',
    },
    {
      code: 'REF_5',
      title: 'Пригласить 100 друзей',
      desc: 'Самый высокий реферальный уровень: 100 приглашённых друзей и мощный бонус в ответ.',
      xp: 900,
      sms: 200,
      promo: '30%',
      check_type: 'auto_ref',
      status: 'pending',
    },
  ],

  usage: [
    {
      code: 'USE_1',
      title: '30 вопросов боту',
      desc: 'Задай 30 вопросов (Таро + Гороскоп) и познакомься с возможностями бота.',
      xp: 50,
      sms: 5,
      promo: null,
      check_type: 'auto_usage',
      status: 'pending',
    },
    {
      code: 'USE_2',
      title: '50 вопросов боту',
      desc: 'Сделай 50 запросов — чем чаще практикуешь, тем тоньше чувствуешь подсказки.',
      xp: 80,
      sms: 10,
      promo: null,
      check_type: 'auto_usage',
      status: 'pending',
    },
    {
      code: 'USE_3',
      title: '100 вопросов боту',
      desc: 'Сто запросов — это уже целая история взаимодействия с ботом.',
      xp: 150,
      sms: 25,
      promo: '5%',
      check_type: 'auto_usage',
      status: 'pending',
    },
    {
      code: 'USE_4',
      title: '300 вопросов боту',
      desc: 'Три сотни вопросов — глубинное знакомство с картами и ритуалами.',
      xp: 300,
      sms: 50,
      promo: '10%',
      check_type: 'auto_usage',
      status: 'pending',
    },
    {
      code: 'USE_5',
      title: '1000 вопросов боту',
      desc: 'Ты — одна из самых активных участниц проекта. Тысяча вопросов — серьёзный путь.',
      xp: 800,
      sms: 150,
      promo: '25%',
      check_type: 'auto_usage',
      status: 'pending',
    },
  ],

  purchases: [
    {
      code: 'BUY_0',
      title: 'Первая покупка',
      desc: 'Сделай первую покупку сообщений в любом объёме — попробуй, как работает платный доступ.',
      xp: 50,
      sms: 5,
      promo: '3%',
      check_type: 'auto_buy',
      status: 'pending',
    },
    {
      code: 'BUY_1',
      title: 'Купить 100 платных сообщений',
      desc: 'Собери 100 купленных платных сообщений (за всё время).',
      xp: 80,
      sms: 10,
      promo: '5%',
      check_type: 'auto_buy',
      status: 'pending',
    },
    {
      code: 'BUY_2',
      title: 'Купить 300 платных сообщений',
      desc: 'Когда есть запас сообщений, можно практиковать глубже и чаще.',
      xp: 150,
      sms: 30,
      promo: '10%',
      check_type: 'auto_buy',
      status: 'pending',
    },
    {
      code: 'BUY_3',
      title: 'Купить 800 платных сообщений',
      desc: '800 сообщений — серьёзный кредит доверия к проекту, благодарим за поддержку.',
      xp: 300,
      sms: 80,
      promo: '20%',
      check_type: 'auto_buy',
      status: 'pending',
    },
    {
      code: 'BUY_4',
      title: 'Купить 1500 платных сообщений',
      desc: 'Ты одна из самых вовлечённых участниц — твоя практика уже стала частью пути.',
      xp: 750,
      sms: 150,
      promo: '25%',
      check_type: 'auto_buy',
      status: 'pending',
    },
    {
      code: 'BUY_5',
      title: 'Купить 3000 платных сообщений',
      desc: 'Максимальный уровень доверия: 3000 купленных сообщений за всё время.',
      xp: 1500,
      sms: 300,
      promo: '30%',
      check_type: 'auto_buy',
      status: 'pending',
    },
  ],

  levels: [
    {
      code: 'LEVEL_UP_1',
      title: 'Достигнуть уровня 2',
      desc: 'Подними статус до уровня 2 «Искатель» (100 XP) и получи дополнительную награду.',
      xp: 20,
      sms: 0,
      promo: null,
      check_type: 'auto_level',
      status: 'pending',
    },
    {
      code: 'LEVEL_UP_2',
      title: 'Достигнуть уровня 3',
      desc: 'Дойди до уровня 3 «Практик» (300 XP) — стабильная работа с практиками.',
      xp: 30,
      sms: 10,
      promo: null,
      check_type: 'auto_level',
      status: 'pending',
    },
    {
      code: 'LEVEL_UP_3',
      title: 'Достигнуть уровня 4',
      desc: 'Поднимись до уровня 4 «Идущая» (700 XP) — системная глубинная работа.',
      xp: 50,
      sms: 30,
      promo: null,
      check_type: 'auto_level',
      status: 'pending',
    },
    {
      code: 'LEVEL_UP_4',
      title: 'Достигнуть уровня 5',
      desc: 'Уровень 5 «Верная» (1200 XP) — ты уже эксперт в совместной работе с ботом.',
      xp: 100,
      sms: 80,
      promo: null,
      check_type: 'auto_level',
      status: 'pending',
    },
    {
      code: 'LEVEL_UP_5',
      title: 'Достигнуть уровня 6',
      desc: 'Уровень 6 «Верховная Мистерия» (3000 XP) — максимальное достижение в системе статусов.',
      xp: 150,
      sms: 150,
      promo: null,
      check_type: 'auto_level',
      status: 'pending',
    },
  ],
};

